# Generated by Django 3.2 on 2023-02-24 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adv_img', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myimage',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adv_img.tier'),
        ),
    ]
