# Generated by Django 3.2 on 2023-02-24 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv_img', '0002_myimage_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myimage',
            name='tier',
        ),
    ]
