# Generated by Django 3.2 on 2023-02-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_img', '0003_remove_myimage_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='myimage',
            name='thumbnail_200',
            field=models.ImageField(blank=True, null=True, upload_to='images_v2/thumbnails/200/'),
        ),
        migrations.AddField(
            model_name='myimage',
            name='thumbnail_400',
            field=models.ImageField(blank=True, null=True, upload_to='images_v2/thumbnails/400/'),
        ),
    ]
